/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LibSift_namespace_LibSiftActivity */

#ifndef _Included_com_LibSift_namespace_LibSiftActivity
#define _Included_com_LibSift_namespace_LibSiftActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_LibSift_namespace_SiftFun_siftConjunction
  (JNIEnv * env, jclass cls, jstring filename1, jstring filename2);
  
#ifdef __cplusplus
}
#endif
#endif
